### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by Siegrift** [lifeomic/attempt#48]
Hi, 

I am using your library in one of our projects and have discovered a bug, which leads to an unhandled promise rejection.

I've investigated the problem and found the problem. The issue arises when you use retry function with timeout and custom handle timeout and the problem is on this line: https://github.com/lifeomic/attempt/blob/3da9c04a7d6bb3670df7c83ff9c21f9abfe36538/src/index.ts#L187
which leads to an error being thrown https://github.com/lifeomic/attempt/blob/3da9c04a7d6bb3670df7c83ff9c21f9abfe36538/src/index.ts#L146

The problem is that the `resolve(onError(err))` is missing a catch statement. There are multiple fixes, but I think the easiest one is to change https://github.com/lifeomic/attempt/blob/3da9c04a7d6bb3670df7c83ff9c21f9abfe36538/src/index.ts#L187 from `resolve(onError(err));` to `onError(err).then(resolve).catch(resolve);`

**Comment by mdlavin** [comment]
Thanks for reporting this problem. I spent some time looking into your explanation and trying to reproduce it for myself. I could not reproduce it. Here is what I found:

In your suggestion, line 187 the `onError` method is an `async` function so even if the throw on line 146 happens, it will be converted into a rejected Promise and handled correctly when returned to `resolve` on line 187. I tried a couple variations of test cases to reproducing and I could not find a way.

Can you create a testcase to demonate the problem?

**Comment by Siegrift** [comment]
Hi, this nodejs snippet demonstarates the problem:

```javascript
const { retry } = require('@lifeomic/attempt')

const go = async (fn, timeoutMs) => {
  const attemptOptions = {
    delay: 200,
    maxAttempts: 1,
    initialDelay: 0,
    minDelay: 0,
    maxDelay: 0,
    factor: 0,
    timeout: timeoutMs,
    jitter: false,
    handleError: null,
    handleTimeout: timeoutMs
      ? async (context, options) => {
          if (context.attemptsRemaining > 0) {
            const res = await retry(fn, { ...options, maxAttempts: context.attemptsRemaining })
            if (res) return res
          }
          throw new Error(`Operation timed out`)
        }
      : null,
    beforeAttempt: null,
    calculateDelay: null,
  }

  return retry(fn, attemptOptions)
}

const main = async () => {
  try {
    await go(async () => {
      await new Promise((res) => setTimeout(res, 2000))
      throw new Error('This causes unhandled rejection')
    }, 1000)
  } catch (e) {
    console.log('Main:', e)
  }
}

main()

```

**Comment by mdlavin** [comment]
Thank you for your testcase. It helped me find a unit test to demonstrate the problem. I'll get it into a released version tomorrow
